Tuoterekisteri/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tuoterekisteri.Models;

namespace Tuoterekisteri.Controllers
{
    public class LoansController : Controller
    {
        LaitehallintaEntities db = new LaitehallintaEntities();
        // GET: Loans
        public ActionResult Index()
        {
            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {
                try
                {
                    List<Loan> model = db.Loans.ToList();
                   
                    return View(model);
                }
                catch (Exception)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    throw;
                }
                finally {  }
            }
            else return RedirectToAction("login", "Users");
        }


        public ActionResult Create()
        {
            if (Session["UserName"] != null && Session["Permission"].ToString() == "1")
            {
                return View();
            }
            else return RedirectToAction("Index", "Home");
        }
        [HttpPost]
        public ActionResult Create([Bind(Include = "user_id, location_id, product_id, loaned_date, spec_id, status")] Loan newLoan)
        {
            if (ModelState.IsValid && Session["UserName"] != null && Session["Permission"].ToString() == "1")
            {
                try
                {
                    db.Loans.Add(newLoan);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.CreateLoanError = T.txt[26, L.nr];
                    return View();
                }

            }
            return View(User);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Loan loan = db.Loans.Find(id);
            if (loan == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            if (Session["UserName"] != null && Session["Permission"].ToString() == "1")
            {
                return View(loan);
            }
            else return RedirectToAction("Index");
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["UserName"] != null && Session["Permission"].ToString() == "1")
            {
                try
                {
                    Loan loan = db.Loans.Find(id);

                    db.Loans.Remove(loan);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    ViewBag.DeleteUserError = T.txt[27, L.nr];
                    return View();
                }

            }
            else return RedirectToAction("Index");
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {
                Loan loan = db.Loans.Find(id);
                if (loan == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                return View(loan);
            }
            else return RedirectToAction("login", "Users");
        }
    }
    }

Tuoterekisteri/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tuoterekisteri.Models;

namespace Tuoterekisteri.Controllers
{
    public class LocationsController : Controller
    {
        private LaitehallintaEntities db = new LaitehallintaEntities();


        // GET: Locations
        public ActionResult Index()
        {
            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {
                return View(db.Locations.ToList());
            }
            else return RedirectToAction("Index", "Home");
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
            }
            else return RedirectToAction("Index", "Home");
        }

        // GET: Locations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "location_id,location_name,location_row2")] Location location)
        {
            
            if (Session["Permission"] != null && Session["Permission"].ToString() == "1" )
            {
                if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
            }
            else return RedirectToAction("Index", "Home");
        }

        // GET: Locations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
            }
            else return RedirectToAction("Index", "Home");
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "location_id,location_name,location_row2")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        public ActionResult Delete(int? id)
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);

            }
            else return RedirectToAction("Index", "Home");
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");

            }
            else return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tuoterekisteri/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tuoterekisteri.Models;

namespace Tuoterekisteri.Controllers
{
    public class ProductsController : Controller
    {
        private LaitehallintaEntities db = new LaitehallintaEntities();

        // GET: Products
        public ActionResult Index()
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {

            var products = db.Products.Include(p => p.Productgroup);
            return View(products.ToList());


            }
            else return RedirectToAction("Index", "Home");

        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {


                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);

            }
            else return RedirectToAction("Index", "Home");

        }

        // GET: Products/Create
        public ActionResult Create()
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {
                ViewBag.product_group_id = new SelectList(db.Productgroups, "product_group_id", "product_group_name");
            return View();


            }
            else return RedirectToAction("Index", "Home");

        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,barcode,product_name,product_row2,product_group_id")] Product product)
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {



                if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.product_group_id = new SelectList(db.Productgroups, "product_group_id", "product_group_name", product.product_group_id);
            return View(product);

            }
            else return RedirectToAction("Index", "Home");

        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {

                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.product_group_id = new SelectList(db.Productgroups, "product_group_id", "product_group_name", product.product_group_id);
            return View(product);


            }
            else return RedirectToAction("Index", "Home");

        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,barcode,product_name,product_row2,product_group_id")] Product product)
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {
                if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.product_group_id = new SelectList(db.Productgroups, "product_group_id", "product_group_name", product.product_group_id);
            return View(product);


            }
            else return RedirectToAction("Index", "Home");

        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {

                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);



            }
            else return RedirectToAction("Index", "Home");

        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
            {

                Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");

            }
            else return RedirectToAction("Index", "Home");

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tuoterekisteri/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Careeria</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               @Html.ActionLink("Careeria" , "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">




                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="" role="button" aria-haspopup="true" aria-expanded="false"><img src="~/images/@(T.txt[0, L.nr]).png" alt="flag"></a>
                        <div class="dropdown-menu" style="">
                            @for (int i = 0; i < L.tot; i++)
                            {
                                if (i != L.nr)
                                {
                                    <ul class="dropdown-item"> @Html.ActionLink((T.txt[0, i]), (T.txt[0, i]), "Home") </ul>
                                }
                            }

                        </div>
                    </li>

                    @if (Session["UserName"] == null)
                    {
                        <li>@Html.ActionLink(T.txt[1, L.nr], "Login", "Users")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink(T.txt[6, L.nr], "Logout", "Users")</li>
                        <li>@Html.ActionLink(T.txt[43, L.nr], "Create", "Loanx")</li>
                        <li>@Html.ActionLink(T.txt[42, L.nr], "Return", "Loanx")</li>
                    }

                    @if (Session["Permission"] != null && Session["Permission"].ToString() == "1")
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
                            <div class="dropdown-menu" style="">
                                <ul class="dropdown-item">@Html.ActionLink(T.txt[12, L.nr], "Index", "Users")</ul>
                                <ul class="dropdown-item">@Html.ActionLink(T.txt[13, L.nr], "Index", "Locations")</ul>
                                <ul class="dropdown-item">@Html.ActionLink(T.txt[7, L.nr], "Index", "Products")</ul>
                                <ul class="dropdown-item">@Html.ActionLink(T.txt[20, L.nr], "Index", "Productgroups")</ul>
                                <ul class="dropdown-item">@Html.ActionLink(T.txt[29, L.nr], "Index", "Specifications")</ul>
                                <ul class="dropdown-item">@Html.ActionLink(T.txt[38, L.nr], "Index", "Loans")</ul>
                            </div>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        
        @RenderBody()

        <footer>
            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>